with open("src/app/pages/04-balance/BulkPayment.tsx", "r") as f:
    lines = f.readlines()

new_lines = []
skip = False
for i, line in enumerate(lines):
    if "                            {activeBalanceSection === \"III\" && (" in line:
        new_lines.append(line)
        new_lines.append("                              <>\n")
        new_lines.append("                                {buEntries3.length > 0 ? (\n")
        new_lines.append("                                  buEntries3.map(([biz, amt]) => (\n")
        new_lines.append("                                    <div key={biz} className=\"flex justify-between items-center text-[10px]\">\n")
        new_lines.append("                                      <span className=\"text-emerald-800/80 font-semibold font-sans flex items-center gap-1.5\">\n")
        new_lines.append("                                        <div className=\"w-1.5 h-1.5 bg-emerald-400 rounded-sm\"></div> {biz}:\n")
        new_lines.append("                                      </span>\n")
        new_lines.append("                                      <span className=\"font-bold text-emerald-950 font-mono tracking-tight\">\n")
        new_lines.append("                                        {formatMoneyVND(amt).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                      </span>\n")
        new_lines.append("                                    </div>\n")
        new_lines.append("                                  ))\n")
        new_lines.append("                                ) : (\n")
        new_lines.append("                                  <span className=\"text-[10px] text-emerald-400 italic\">Không có dữ liệu</span>\n")
        new_lines.append("                                )}\n")
        new_lines.append("                                <div className=\"flex justify-between items-center mt-2 pt-2 border-t border-emerald-200/50 font-bold text-emerald-950 text-[10px] tracking-wider uppercase\">\n")
        new_lines.append("                                  <span>TOTAL NET PAY:</span>\n")
        new_lines.append("                                  <span className=\"font-black text-emerald-700 font-mono tracking-tight\">{formatMoneyVND(netPayTotal).replace(\" ₫\", \"\")}</span>\n")
        new_lines.append("                                </div>\n")
        new_lines.append("                              </>\n")
        new_lines.append("                            )}\n")
        new_lines.append("\n")
        new_lines.append("                            {activeBalanceSection === \"IV\" && (\n")
        new_lines.append("                              <div className=\"flex flex-col gap-2 pt-1 text-[10.5px]\">\n")
        new_lines.append("                                <div className=\"flex justify-between items-center border-b border-sky-100/50 pb-1.5\">\n")
        new_lines.append("                                  <span className=\"text-sky-900 font-bold font-sans flex items-center gap-1.5 tracking-wide\">\n")
        new_lines.append("                                    <div className=\"w-1.5 h-1.5 bg-sky-400 rounded-full\"></div> TỔNG AE:\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                  <span className=\"font-bold text-sky-700 font-mono tracking-tight\">\n")
        new_lines.append("                                    {formatMoneyVND(totalBulkPayment).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                </div>\n")
        new_lines.append("                                \n")
        new_lines.append("                                <div className=\"flex justify-between items-center\">\n")
        new_lines.append("                                  <span className=\"text-sky-900 font-bold font-sans flex items-center gap-1.5 tracking-wide\">\n")
        new_lines.append("                                    <div className=\"w-1.5 h-1.5 bg-sky-400 rounded-full\"></div> TỔNG ACC:\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                  <span className=\"font-bold text-sky-700 font-mono tracking-tight\">\n")
        new_lines.append("                                    {formatMoneyVND(totalAcc).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                </div>\n")
        new_lines.append("                                \n")
        new_lines.append("                                <div className=\"flex flex-col gap-1 pl-4 border-l-2 border-sky-200/50 my-1 py-1\">\n")
        new_lines.append("                                  <div className=\"flex justify-between items-center text-[10px]\">\n")
        new_lines.append("                                    <span className=\"text-sky-800/80 font-semibold font-sans flex items-center gap-1.5\">\n")
        new_lines.append("                                      <div className=\"w-1 h-1 bg-sky-300 rounded-sm\"></div> BONUS:\n")
        new_lines.append("                                    </span>\n")
        new_lines.append("                                    <span className=\"font-semibold text-sky-900 font-mono tracking-tight\">\n")
        new_lines.append("                                      {formatMoneyVND(bonusTotal).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                    </span>\n")
        new_lines.append("                                  </div>\n")
        new_lines.append("                                  <div className=\"flex justify-between items-center text-[10px]\">\n")
        new_lines.append("                                    <span className=\"text-sky-800/80 font-semibold font-sans flex items-center gap-1.5\">\n")
        new_lines.append("                                      <div className=\"w-1 h-1 bg-sky-300 rounded-sm\"></div> HOLD:\n")
        new_lines.append("                                    </span>\n")
        new_lines.append("                                    <span className=\"font-semibold text-rose-500 font-mono tracking-tight\">\n")
        new_lines.append("                                      -{formatMoneyVND(sameMonthHold).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                    </span>\n")
        new_lines.append("                                  </div>\n")
        new_lines.append("                                  <div className=\"flex justify-between items-center text-[10px]\">\n")
        new_lines.append("                                    <span className=\"text-sky-800/80 font-semibold font-sans flex items-center gap-1.5\">\n")
        new_lines.append("                                      <div className=\"w-1 h-1 bg-sky-300 rounded-sm\"></div> ADD:\n")
        new_lines.append("                                    </span>\n")
        new_lines.append("                                    <span className=\"font-semibold text-emerald-500 font-mono tracking-tight\">\n")
        new_lines.append("                                      +{formatMoneyVND(diffMonthAdd).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                    </span>\n")
        new_lines.append("                                  </div>\n")
        new_lines.append("                                </div>\n")
        new_lines.append("\n")
        new_lines.append("                                <div className=\"flex justify-between items-center border-t border-sky-100/50 pt-2\">\n")
        new_lines.append("                                  <span className=\"text-sky-900 font-bold font-sans flex items-center gap-1.5 tracking-wide\">\n")
        new_lines.append("                                    <div className=\"w-1.5 h-1.5 bg-sky-400 rounded-full\"></div> TỔNG BANK AE:\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                  <span className=\"font-bold text-sky-700 font-mono tracking-tight\">\n")
        new_lines.append("                                    {formatMoneyVND(totalBankAe).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                </div>\n")
        new_lines.append("\n")
        new_lines.append("                                <div className=\"flex justify-between items-center border-t border-sky-200/60 mt-1 pt-2\">\n")
        new_lines.append("                                  <span className=\"font-bold text-sky-950 font-sans text-[10px] tracking-wider uppercase\">\n")
        new_lines.append("                                    LỆCH (DIFF):\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                  <span className={`font-black font-mono tracking-tight ${diff !== 0 ? \"text-rose-600 bg-rose-50 px-1.5 rounded\" : \"text-emerald-600 bg-emerald-50 px-1.5 rounded\"}`}>\n")
        new_lines.append("                                    {formatMoneyVND(diff).replace(\" ₫\", \"\")}\n")
        new_lines.append("                                  </span>\n")
        new_lines.append("                                </div>\n")
        new_lines.append("                              </div>\n")
        new_lines.append("                            )}\n")
        skip = True
        continue
    
    if skip:
        if "                          </div>" in line and "</div>" in lines[i+1] and "          </div>" not in lines[i+2]:
            skip = False
        continue
        
    new_lines.append(line)

with open("src/app/pages/04-balance/BulkPayment.tsx", "w") as f:
    f.writelines(new_lines)
